### ISSUE TITLE
Use a Computer across threads

### ISSUE THREAD

**Issue by dlee13** [asmoaesl/rsc#6]
How do I make it thread-safe? I want to use a Computer across threads using `std::sync::Arc`, but the error says `missing lifetime specifier`. If I write 'static, it says `help: the trait 'std::marker::Sync' is not implemented for 'dyn std::ops::Fn(f64) -> f64 + 'static)'`

**Comment by asmoaesl** [comment]
Oh, I think I can correct this tonight on the master branch.

**Comment by asmoaesl** [comment]
Can you send me the code you were trying to write? Show me the code you wrote where the error was `missing lifetime specifier`. Thanks.

**Comment by dlee13** [comment]
Thanks, here is an example:
https://gist.github.com/dlee13/47f0f826b87370fe7c899feb452f57ec

**Comment by dlee13** [comment]
Or how about just adding Serde as an optional feature?

**Comment by asmoaesl** [comment]
So in your error, it says that you must specify a lifetime for `Computer`. That is because `Computer` has functions that can be added at runtime, and if you use a closure (a type of function that may not be known at runtime, thus needs a reference) then you have to specify the lifetime of those functions. If you do not use closures, then you can simply specify a `'static` lifetime, which should work for almost everything. Here is [line 16 of your code](https://gist.github.com/dlee13/47f0f826b87370fe7c899feb452f57ec#file-main-rs-L16) corrected:
```rust
type Value = Arc<RwLock<Computer<'static, f64>>>;
```
Let me know if that fixes your problem. Thanks for using my library! I appreciate it :smiley:

**Comment by dlee13** [comment]
That does fix the first error, but there's still the second. `help: the trait 'std::marker::Sync' is not implemented for 'dyn std::ops::Fn(f64) -> f64 + 'static)'`

**Comment by asmoaesl** [comment]
I think there's a deeper issue here. You will not be able to pass a `Computer` object around without removing the function pointers (`Computer.functions`) from the RSC source that you're building, unless I'm not thinking clearly (very possible). So you could just as effectively pass only the `HashMap` of variables around, or whatever you care about, and then construct a Computer struct on the spot when you need it. Otherwise, whatever cannot be synced must be ditched.

I'm sorry this is very inconvenient. It was designed for performance and convenience in simpler scenarios, but it becomes really complicated in multi-threaded ones.

But all said, I did design it with the intentions for anyone to be capable of changing it. You have free reign to do as you wish to make it conform to however you want. You may also be interested in using a 1.x release, which did not have dynamic runtime functions.

**Comment by dlee13** [comment]
Thank you. I'll play with it later and figure something out.
